# Generated by Django 4.1.2 on 2022-10-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pres', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pres',
            options={'ordering': ['-created_at'], 'verbose_name': 'Презентация', 'verbose_name_plural': 'Презентации'},
        ),
        migrations.AlterField(
            model_name='pres',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pres',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='pres',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/%d/', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='pres',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Отображается?'),
        ),
        migrations.AlterField(
            model_name='pres',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='pres',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
