# Generated by Django 4.1.2 on 2022-10-24 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pres', '0003_category_pres_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pres',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pres.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='pres',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Отображается?'),
        ),
    ]
