# Generated by Django 4.1.2 on 2022-10-31 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pres', '0004_alter_pres_category_alter_pres_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='pres',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pres',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_pres', to='pres.category', verbose_name='Категория'),
        ),
    ]
